spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ait
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
